version: "3.8"

services:
  expense-fe:
    container_name: expense-fe
    build:
      context: ./expense-fe
      dockerfile: dev.Dockerfile
      # args:
      #   - ANY_TOKEN
    command: ['npm','run','start']
    restart: on-failure
    volumes:
      - ./expense-fe/src:/app/src:delegate
      - ./expense-fe/public:/app/public:delegate
    ports:
      - 3000:3000
    environment:
      VIRTUAL_HOST: 'fe.expense.docker'
    networks:
      - expense-manger

  expense-be:
    container_name: expense-be
    build:
      context: ./expense-be
      dockerfile: dev.Dockerfile
      # args:
      #   - ANY_TOKEN
    command: ['npm','run','start:dev']
    restart: on-failure
    depends_on:
      - db-postgres-service
    volumes:
      - ./expense-be/src:/app/src:delegate
    ports:
      - 3001:3001
    environment:
      VIRTUAL_HOST: 'be.expense.docker'
    networks:
      - expense-manger
  db-postgres-service:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'expense'
    ports:
    - 54321:54321
    networks:
    - expense-manger
  db-postgres-client:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin4
    depends_on:
      - db-postgres-service
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
    - 5050:80
    networks:
    - expense-manger
networks:
  expense-manger: